# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [24]:
import sys
!{sys.executable} -m pip install pandas-datareader

Requirement already satisfied: pandas-datareader in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (0.11.1)
Requirement already satisfied: lxml in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from pandas-datareader) (6.1.3)
Requirement already satisfied: pandas>=2.1.4 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from pandas-datareader) (3.0.5)
Requirement already satisfied: requests>=2.19.0 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from pandas-datareader) (2.34.2)
Requirement already satisfied: setuptools in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from pandas-datareader) (83.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.4->pandas-datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\User\anaconda3\envs\py313\Lib\site-packages (from requests>=2.19.0->pandas-datareader) (2026.7.22)

In [25]:
import pandas as pd
import pandas_datareader.data as web
from datetime import datetime

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [26]:
start = '2015-01-01'
end = datetime.today()

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

In [27]:
api_key = 'B77QBHTUPCLG8G7N'

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [28]:
import pandas_datareader as pdr
print(pdr.__version__)

0.11.1

In [29]:
!pip install yfinance

Requirement already satisfied: yfinance in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (6.1.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (2.5.3)
Requirement already satisfied: pandas>=1.3.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (3.0.5)
Requirement already satisfied: peewee>=3.16.2 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (4.11.7)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (7.36.1)
Requirement already satisfied: pytz>=2022.5 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (2026.3.post1)
Requirement already satisfied: requests>=2.31 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (2.34.2)
Requirement already satisfied: websockets>=13.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from yfinance) (17.1)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: pycparser in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=1.3.0->yfinance) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from requests>=2.31->yfinance) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\user\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from requests>=2.31->yfinance) (2.7.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [30]:
import requests
import pandas as pd

url = "https://www.alphavantage.co/query"

params = {
    "function": "TIME_SERIES_DAILY",
    "symbol": "AAPL",
    "outputsize": "compact",
    "apikey": api_key
}

response = requests.get(url, params=params)
data = response.json()

df_apple = pd.DataFrame.from_dict(
    data["Time Series (Daily)"],
    orient="index"
)

df_apple.index = pd.to_datetime(df_apple.index)
df_apple = df_apple.sort_index()

df_apple.columns = ['open', 'high', 'low', 'close', 'volume']

print(df_apple)

                open      high       low     close    volume
2026-04-15  258.1600  266.5600  257.8100  266.4300  49913510
2026-04-16  266.8000  267.1600  261.2700  263.4000  43323112
2026-04-17  266.9600  272.3000  266.7200  270.2300  61436228
2026-04-20  270.3300  274.2750  270.2900  273.0500  36590169
2026-04-21  271.5000  272.8000  265.4000  266.1700  50209755
...              ...       ...       ...       ...       ...
2026-08-31  319.6000  321.2350  312.8000  316.8500  41242724
2026-09-01  316.9800  327.3000  314.7300  325.1300  53167388
2026-09-02  326.8650  328.4000  323.5300  324.9600  33776370
2026-09-03  324.8700  330.8100  324.1100  328.2100  37225838
2026-09-04  328.3050  328.9300  317.8600  319.9700  39606884

[100 rows x 5 columns]

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [31]:
df_apple['stock'] = 'AAPL'
df_apple

                open      high       low     close    volume stock
2026-04-15  258.1600  266.5600  257.8100  266.4300  49913510  AAPL
2026-04-16  266.8000  267.1600  261.2700  263.4000  43323112  AAPL
2026-04-17  266.9600  272.3000  266.7200  270.2300  61436228  AAPL
2026-04-20  270.3300  274.2750  270.2900  273.0500  36590169  AAPL
2026-04-21  271.5000  272.8000  265.4000  266.1700  50209755  AAPL
...              ...       ...       ...       ...       ...   ...
2026-08-31  319.6000  321.2350  312.8000  316.8500  41242724  AAPL
2026-09-01  316.9800  327.3000  314.7300  325.1300  53167388  AAPL
2026-09-02  326.8650  328.4000  323.5300  324.9600  33776370  AAPL
2026-09-03  324.8700  330.8100  324.1100  328.2100  37225838  AAPL
2026-09-04  328.3050  328.9300  317.8600  319.9700  39606884  AAPL

[100 rows x 6 columns]

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [32]:
print(data)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'AAPL', '3. Last Refreshed': '2026-09-04', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2026-09-04': {'1. open': '328.3050', '2. high': '328.9300', '3. low': '317.8600', '4. close': '319.9700', '5. volume': '39606884'}, '2026-09-03': {'1. open': '324.8700', '2. high': '330.8100', '3. low': '324.1100', '4. close': '328.2100', '5. volume': '37225838'}, '2026-09-02': {'1. open': '326.8650', '2. high': '328.4000', '3. low': '323.5300', '4. close': '324.9600', '5. volume': '33776370'}, '2026-09-01': {'1. open': '316.9800', '2. high': '327.3000', '3. low': '314.7300', '4. close': '325.1300', '5. volume': '53167388'}, '2026-08-31': {'1. open': '319.6000', '2. high': '321.2350', '3. low': '312.8000', '4. close': '316.8500', '5. volume': '41242724'}, '2026-08-28': {'1. open': '316.8450', '2. high': '322.3700', '3. low': '315.4504', '4. close': '319.7000', '5. volume': '38649398'}, '2026-08-27': {'1. open': '310.5450', '2. high': '315.4000', '3. low': '309.4001', '4. close': '314.5800', '5. volume': '32419233'}, '2026-08-26': {'1. open': '310.3000', '2. high': '315.4300', '3. low': '308.8001', '4. close': '313.4500', '5. volume': '34024486'}, '2026-08-25': {'1. open': '310.7900', '2. high': '313.5900', '3. low': '308.2100', '4. close': '309.9000', '5. volume': '25869807'}, '2026-08-24': {'1. open': '311.4700', '2. high': '313.3600', '3. low': '309.9700', '4. close': '310.3400', '5. volume': '34673582'}, '2026-08-21': {'1. open': '312.0500', '2. high': '312.3800', '3. low': '307.0100', '4. close': '309.3500', '5. volume': '46876815'}, '2026-08-20': {'1. open': '317.4550', '2. high': '320.2800', '3. low': '310.6500', '4. close': '311.3000', '5. volume': '40959184'}, '2026-08-19': {'1. open': '310.1400', '2. high': '319.2799', '3. low': '309.6000', '4. close': '316.8300', '5. volume': '50505646'}, '2026-08-18': {'1. open': '307.5800', '2. high': '311.4900', '3. low': '305.7400', '4. close': '310.0300', '5. volume': '53424535'}, '2026-08-17': {'1. open': '306.2100', '2. high': '307.6600', '3. low': '302.9390', '4. close': '305.5900', '5. volume': '38169263'}, '2026-08-14': {'1. open': '306.0000', '2. high': '307.4900', '3. low': '304.3000', '4. close': '305.9300', '5. volume': '28229375'}, '2026-08-13': {'1. open': '304.2100', '2. high': '306.0000', '3. low': '302.0500', '4. close': '305.2600', '5. volume': '40349289'}, '2026-08-12': {'1. open': '305.1000', '2. high': '305.6600', '3. low': '300.5700', '4. close': '302.2500', '5. volume': '41657768'}, '2026-08-11': {'1. open': '307.7500', '2. high': '309.9700', '3. low': '302.7900', '4. close': '304.9100', '5. volume': '37476746'}, '2026-08-10': {'1. open': '306.8300', '2. high': '308.2600', '3. low': '304.6100', '4. close': '308.2600', '5. volume': '44812503'}, '2026-08-07': {'1. open': '311.4500', '2. high': '314.8100', '3. low': '310.7400', '4. close': '313.3300', '5. volume': '34437191'}, '2026-08-06': {'1. open': '314.3400', '2. high': '316.2894', '3. low': '309.2300', '4. close': '312.4100', '5. volume': '46139901'}, '2026-08-05': {'1. open': '309.3600', '2. high': '311.7100', '3. low': '305.6700', '4. close': '311.0000', '5. volume': '49438763'}, '2026-08-04': {'1. open': '302.7250', '2. high': '310.4200', '3. low': '301.3200', '4. close': '309.3800', '5. volume': '68000969'}, '2026-08-03': {'1. open': '309.5800', '2. high': '311.8000', '3. low': '302.5600', '4. close': '303.4200', '5. volume': '75051951'}, '2026-07-31': {'1. open': '304.8100', '2. high': '310.6900', '3. low': '300.0000', '4. close': '308.9100', '5. volume': '132489137'}, '2026-07-30': {'1. open': '333.1000', '2. high': '334.7500', '3. low': '329.5900', '4. close': '333.4300', '5. volume': '74817792'}, '2026-07-29': {'1. open': '339.7300', '2. high': '344.5699', '3. low': '337.3501', '4. close': '338.1900', '5. volume': '56090840'}, '2026-07-28': {'1. open': '340.0300', '2. high': '342.8900', '3. low': '335.6000', '4. close': '340.0800', '5. volume': '51859042'}, '2026-07-27': {'1. open': '334.5400', '2. high': '339.5700', '3. low': '334.0200', '4. close': '336.9100', '5. volume': '49604297'}, '2026-07-24': {'1. open': '321.7900', '2. high': '334.3700', '3. low': '321.6200', '4. close': '333.0200', '5. volume': '47489415'}, '2026-07-23': {'1. open': '321.7300', '2. high': '323.3000', '3. low': '319.3500', '4. close': '321.6600', '5. volume': '40840778'}, '2026-07-22': {'1. open': '327.8700', '2. high': '328.9995', '3. low': '323.3400', '4. close': '325.8900', '5. volume': '38755929'}, '2026-07-21': {'1. open': '323.1300', '2. high': '329.6000', '3. low': '322.2204', '4. close': '327.7400', '5. volume': '41338917'}, '2026-07-20': {'1. open': '333.5050', '2. high': '333.7100', '3. low': '323.6800', '4. close': '326.5900', '5. volume': '53468008'}, '2026-07-17': {'1. open': '331.9800', '2. high': '334.9900', '3. low': '329.0006', '4. close': '333.7400', '5. volume': '63407059'}, '2026-07-16': {'1. open': '328.0050', '2. high': '334.6800', '3. low': '326.7900', '4. close': '333.2600', '5. volume': '62970617'}, '2026-07-15': {'1. open': '317.6150', '2. high': '328.7300', '3. low': '317.3200', '4. close': '327.5000', '5. volume': '60957644'}, '2026-07-14': {'1. open': '313.7600', '2. high': '316.1900', '3. low': '311.9100', '4. close': '314.8600', '5. volume': '36336829'}, '2026-07-13': {'1. open': '317.0150', '2. high': '323.4500', '3. low': '315.7800', '4. close': '317.3100', '5. volume': '43257804'}, '2026-07-10': {'1. open': '314.7200', '2. high': '316.9100', '3. low': '312.1700', '4. close': '315.3200', '5. volume': '34132321'}, '2026-07-09': {'1. open': '310.5100', '2. high': '316.5300', '3. low': '308.1600', '4. close': '316.2200', '5. volume': '48124490'}, '2026-07-08': {'1. open': '311.9100', '2. high': '314.8200', '3. low': '307.0500', '4. close': '313.3900', '5. volume': '41323480'}, '2026-07-07': {'1. open': '315.2900', '2. high': '315.4800', '3. low': '310.1500', '4. close': '310.6600', '5. volume': '42490002'}, '2026-07-06': {'1. open': '307.3600', '2. high': '314.2000', '3. low': '307.0000', '4. close': '312.6600', '5. volume': '53589977'}, '2026-07-02': {'1. open': '294.1200', '2. high': '309.4200', '3. low': '293.6800', '4. close': '308.6300', '5. volume': '75400626'}, '2026-07-01': {'1. open': '293.4400', '2. high': '296.5900', '3. low': '289.1950', '4. close': '294.3800', '5. volume': '50164232'}, '2026-06-30': {'1. open': '281.1700', '2. high': '289.9400', '3. low': '280.6950', '4. close': '289.3600', '5. volume': '65100155'}, '2026-06-29': {'1. open': '286.7300', '2. high': '288.3697', '3. low': '279.8500', '4. close': '281.7400', '5. volume': '66427002'}, '2026-06-26': {'1. open': '275.0000', '2. high': '285.9500', '3. low': '274.2100', '4. close': '283.7800', '5. volume': '261775450'}, '2026-06-25': {'1. open': '287.4000', '2. high': '288.8000', '3. low': '273.7500', '4. close': '275.1500', '5. volume': '107253659'}, '2026-06-24': {'1. open': '295.3550', '2. high': '299.7000', '3. low': '292.9400', '4. close': '293.0800', '5. volume': '53081859'}, '2026-06-23': {'1. open': '297.5380', '2. high': '301.6400', '3. low': '294.1800', '4. close': '294.3000', '5. volume': '52010929'}, '2026-06-22': {'1. open': '297.3100', '2. high': '302.4200', '3. low': '296.7600', '4. close': '297.0100', '5. volume': '44879914'}, '2026-06-18': {'1. open': '298.1100', '2. high': '300.5700', '3. low': '295.6200', '4. close': '298.0100', '5. volume': '85962201'}, '2026-06-17': {'1. open': '300.8450', '2. high': '302.0700', '3. low': '294.3600', '4. close': '295.9500', '5. volume': '42745060'}, '2026-06-16': {'1. open': '295.2450', '2. high': '300.4800', '3. low': '293.9700', '4. close': '299.2400', '5. volume': '39874404'}, '2026-06-15': {'1. open': '294.1200', '2. high': '297.7800', '3. low': '291.7000', '4. close': '296.4200', '5. volume': '45732573'}, '2026-06-12': {'1. open': '296.0300', '2. high': '297.1400', '3. low': '289.6200', '4. close': '291.1300', '5. volume': '38784789'}, '2026-06-11': {'1. open': '293.7200', '2. high': '297.0000', '3. low': '289.5900', '4. close': '295.6300', '5. volume': '42572497'}, '2026-06-10': {'1. open': '290.7400', '2. high': '294.7500', '3. low': '287.3800', '4. close': '291.5800', '5. volume': '52793266'}, '2026-06-09': {'1. open': '300.2750', '2. high': '300.7500', '3. low': '287.7800', '4. close': '290.5500', '5. volume': '70108847'}, '2026-06-08': {'1. open': '308.7390', '2. high': '317.4000', '3. low': '301.1700', '4. close': '301.5400', '5. volume': '77949082'}, '2026-06-05': {'1. open': '312.8600', '2. high': '315.1700', '3. low': '307.1500', '4. close': '307.3400', '5. volume': '65310502'}, '2026-06-04': {'1. open': '313.2300', '2. high': '313.5400', '3. low': '309.6500', '4. close': '311.2300', '5. volume': '44869134'}, '2026-06-03': {'1. open': '314.1750', '2. high': '316.9400', '3. low': '308.8500', '4. close': '310.2600', '5. volume': '50836705'}, '2026-06-02': {'1. open': '307.4600', '2. high': '315.4500', '3. low': '306.6850', '4. close': '315.2000', '5. volume': '44534716'}, '2026-06-01': {'1. open': '309.6250', '2. high': '310.9400', '3. low': '305.0200', '4. close': '306.3100', '5. volume': '48849933'}, '2026-05-29': {'1. open': '311.7750', '2. high': '315.0000', '3. low': '309.5300', '4. close': '312.0600', '5. volume': '70026752'}, '2026-05-28': {'1. open': '310.6800', '2. high': '312.8000', '3. low': '309.5700', '4. close': '312.5100', '5. volume': '48220390'}, '2026-05-27': {'1. open': '308.3300', '2. high': '313.2600', '3. low': '308.3000', '4. close': '310.8500', '5. volume': '50430919'}, '2026-05-26': {'1. open': '309.5600', '2. high': '311.8200', '3. low': '307.6700', '4. close': '308.3300', '5. volume': '48000493'}, '2026-05-22': {'1. open': '306.1200', '2. high': '311.4000', '3. low': '305.8400', '4. close': '308.8200', '5. volume': '43670223'}, '2026-05-21': {'1. open': '301.0550', '2. high': '305.5400', '3. low': '300.4000', '4. close': '304.9900', '5. volume': '42965126'}, '2026-05-20': {'1. open': '298.1800', '2. high': '302.8000', '3. low': '298.0800', '4. close': '302.2500', '5. volume': '37307876'}, '2026-05-19': {'1. open': '296.9700', '2. high': '300.5100', '3. low': '296.3500', '4. close': '298.9700', '5. volume': '42243561'}, '2026-05-18': {'1. open': '300.2400', '2. high': '300.6600', '3. low': '294.9100', '4. close': '297.8400', '5. volume': '34482959'}, '2026-05-15': {'1. open': '297.9000', '2. high': '303.2000', '3. low': '296.5200', '4. close': '300.2300', '5. volume': '54862836'}, '2026-05-14': {'1. open': '299.8200', '2. high': '300.4500', '3. low': '295.3800', '4. close': '298.2100', '5. volume': '35324922'}, '2026-05-13': {'1. open': '293.5000', '2. high': '300.9200', '3. low': '293.5000', '4. close': '298.8700', '5. volume': '52684260'}, '2026-05-12': {'1. open': '292.5600', '2. high': '295.2700', '3. low': '292.5600', '4. close': '294.8000', '5. volume': '45748129'}, '2026-05-11': {'1. open': '291.9790', '2. high': '293.8800', '3. low': '290.2300', '4. close': '292.6800', '5. volume': '42247285'}, '2026-05-08': {'1. open': '290.0100', '2. high': '294.7600', '3. low': '290.0000', '4. close': '293.3200', '5. volume': '52692761'}, '2026-05-07': {'1. open': '289.2700', '2. high': '292.1300', '3. low': '285.7800', '4. close': '287.4400', '5. volume': '45224300'}, '2026-05-06': {'1. open': '281.9150', '2. high': '288.0300', '3. low': '281.0700', '4. close': '287.5100', '5. volume': '58336072'}, '2026-05-05': {'1. open': '276.9250', '2. high': '284.5700', '3. low': '276.5010', '4. close': '284.1800', '5. volume': '49311712'}, '2026-05-04': {'1. open': '279.6550', '2. high': '280.6300', '3. low': '274.8601', '4. close': '276.8300', '5. volume': '46668401'}, '2026-05-01': {'1. open': '278.8550', '2. high': '287.2200', '3. low': '278.3700', '4. close': '280.1400', '5. volume': '79915442'}, '2026-04-30': {'1. open': '270.5000', '2. high': '276.0000', '3. low': '268.1400', '4. close': '271.3500', '5. volume': '91848230'}, '2026-04-29': {'1. open': '267.5500', '2. high': '271.0400', '3. low': '267.0400', '4. close': '270.1700', '5. volume': '30047869'}, '2026-04-28': {'1. open': '272.3350', '2. high': '273.2300', '3. low': '268.6600', '4. close': '270.7100', '5. volume': '40018940'}, '2026-04-27': {'1. open': '266.0900', '2. high': '268.3600', '3. low': '265.0700', '4. close': '267.6100', '5. volume': '41466762'}, '2026-04-24': {'1. open': '272.7550', '2. high': '273.0600', '3. low': '269.6500', '4. close': '271.0600', '5. volume': '38157110'}, '2026-04-23': {'1. open': '275.0450', '2. high': '275.7700', '3. low': '271.6500', '4. close': '273.4300', '5. volume': '33399639'}, '2026-04-22': {'1. open': '267.8200', '2. high': '273.7400', '3. low': '266.8700', '4. close': '273.1700', '5. volume': '43249204'}, '2026-04-21': {'1. open': '271.5000', '2. high': '272.8000', '3. low': '265.4000', '4. close': '266.1700', '5. volume': '50209755'}, '2026-04-20': {'1. open': '270.3300', '2. high': '274.2750', '3. low': '270.2900', '4. close': '273.0500', '5. volume': '36590169'}, '2026-04-17': {'1. open': '266.9600', '2. high': '272.3000', '3. low': '266.7200', '4. close': '270.2300', '5. volume': '61436228'}, '2026-04-16': {'1. open': '266.8000', '2. high': '267.1600', '3. low': '261.2700', '4. close': '263.4000', '5. volume': '43323112'}, '2026-04-15': {'1. open': '258.1600', '2. high': '266.5600', '3. low': '257.8100', '4. close': '266.4300', '5. volume': '49913510'}}}

In [33]:
params = {
    "function": "TIME_SERIES_DAILY",
    "symbol": "MSFT",
    "outputsize": "compact",
    "apikey": api_key
}

response = requests.get(url, params=params)
data = response.json()

print(data)

{'Information': 'Thank you for using Alpha Vantage! Please consider spreading out your free API requests more sparingly (1 request per second). You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to lift the free key rate limit (25 requests per day), raise the per-second burst limit, and instantly unlock all premium endpoints'}

In [34]:
params["symbol"] = "IBM"

response = requests.get(url, params=params)
data = response.json()

df_ibm = pd.DataFrame.from_dict(
    data["Time Series (Daily)"],
    orient="index"
)

df_ibm.index = pd.to_datetime(df_ibm.index)
df_ibm = df_ibm.sort_index()
df_ibm.columns = ['open', 'high', 'low', 'close', 'volume']

df_ibm = df_ibm[
    (df_ibm.index >= start) &
    (df_ibm.index <= end)
]

df_ibm['stock'] = 'IBM'

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [37]:
params = {
    "function": "TIME_SERIES_DAILY",
    "symbol": "MSFT",
    "outputsize": "compact",
    "apikey": api_key
}

response = requests.get(url, params=params)
data = response.json()

print(data.keys())

dict_keys(['Meta Data', 'Time Series (Daily)'])

In [38]:
df_microsoft = pd.DataFrame.from_dict(
    data["Time Series (Daily)"],
    orient="index"
)

df_microsoft.index = pd.to_datetime(df_microsoft.index)
df_microsoft = df_microsoft.sort_index()

df_microsoft.columns = ['open', 'high', 'low', 'close', 'volume']

df_microsoft['stock'] = 'MSFT'

df_microsoft

                open      high       low     close    volume stock
2026-04-15  398.0000  414.3699  396.7300  411.2200  45063389  MSFT
2026-04-16  419.8600  420.8200  412.1400  420.2600  41642361  MSFT
2026-04-17  424.8200  431.5800  420.6900  422.7900  48568190  MSFT
2026-04-20  421.1450  423.3300  416.3000  418.0700  27582237  MSFT
2026-04-21  420.2400  427.1800  417.2000  424.1600  32048495  MSFT
...              ...       ...       ...       ...       ...   ...
2026-08-31  510.3800  512.1900  506.3900  507.2900  27208911  MSFT
2026-09-01  497.5200  505.9700  496.7800  501.0200  21046892  MSFT
2026-09-02  499.8500  500.2700  493.8100  496.8200  15336074  MSFT
2026-09-03  501.6600  515.6500  500.8000  510.1200  24125893  MSFT
2026-09-04  510.0000  511.0000  499.3600  499.7000  18101758  MSFT

[100 rows x 6 columns]

In [39]:
df = pd.concat([df_apple, df_tesla, df_ibm, df_microsoft])
df

                open      high       low     close    volume stock
2026-04-15  258.1600  266.5600  257.8100  266.4300  49913510  AAPL
2026-04-16  266.8000  267.1600  261.2700  263.4000  43323112  AAPL
2026-04-17  266.9600  272.3000  266.7200  270.2300  61436228  AAPL
2026-04-20  270.3300  274.2750  270.2900  273.0500  36590169  AAPL
2026-04-21  271.5000  272.8000  265.4000  266.1700  50209755  AAPL
...              ...       ...       ...       ...       ...   ...
2026-08-31  510.3800  512.1900  506.3900  507.2900  27208911  MSFT
2026-09-01  497.5200  505.9700  496.7800  501.0200  21046892  MSFT
2026-09-02  499.8500  500.2700  493.8100  496.8200  15336074  MSFT
2026-09-03  501.6600  515.6500  500.8000  510.1200  24125893  MSFT
2026-09-04  510.0000  511.0000  499.3600  499.7000  18101758  MSFT

[400 rows x 6 columns]

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [40]:
df = df.set_index(['stock', df.index])
df

                      open      high       low     close    volume
stock
AAPL  2026-04-15  258.1600  266.5600  257.8100  266.4300  49913510
      2026-04-16  266.8000  267.1600  261.2700  263.4000  43323112
      2026-04-17  266.9600  272.3000  266.7200  270.2300  61436228
      2026-04-20  270.3300  274.2750  270.2900  273.0500  36590169
      2026-04-21  271.5000  272.8000  265.4000  266.1700  50209755
...                    ...       ...       ...       ...       ...
MSFT  2026-08-31  510.3800  512.1900  506.3900  507.2900  27208911
      2026-09-01  497.5200  505.9700  496.7800  501.0200  21046892
      2026-09-02  499.8500  500.2700  493.8100  496.8200  15336074
      2026-09-03  501.6600  515.6500  500.8000  510.1200  24125893
      2026-09-04  510.0000  511.0000  499.3600  499.7000  18101758

[400 rows x 5 columns]

### Step 7. Create a dataFrame called vol, with the volume values.

In [41]:
vol = df['volume']
vol

stock
AAPL   2026-04-15    49913510
       2026-04-16    43323112
       2026-04-17    61436228
       2026-04-20    36590169
       2026-04-21    50209755
                       ...
MSFT   2026-08-31    27208911
       2026-09-01    21046892
       2026-09-02    15336074
       2026-09-03    24125893
       2026-09-04    18101758
Name: volume, Length: 400, dtype: str

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [42]:
vol = vol.groupby([
    vol.index.get_level_values('stock'),
    vol.index.get_level_values(1).to_period('W')
]).sum()

vol

stock
AAPL   2026-04-13/2026-04-19                    499135104332311261436228
       2026-04-20/2026-04-26    3659016950209755432492043339963938157110
       2026-04-27/2026-05-03    4146676240018940300478699184823079915442
       2026-05-04/2026-05-10    4666840149311712583360724522430052692761
       2026-05-11/2026-05-17    4224728545748129526842603532492254862836
                                                  ...
TSLA   2026-08-03/2026-08-09    3828136233318303278208132603377639492345
       2026-08-10/2026-08-16    2500380823345233286988793470830345437144
       2026-08-17/2026-08-23    2603709327994466367354283076636059223958
       2026-08-24/2026-08-30    3919048429816685285730073013616432972214
       2026-08-31/2026-09-06    6173225836193926339519096360098765018209
Name: volume, Length: 84, dtype: str

### Step 9. Find all the volume traded in the year of 2015

In [43]:
vol_2015 = vol[
    vol.index.get_level_values(1).year == 2015
]

vol_2015

Series([], Name: volume, dtype: str)