# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [8]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [9]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

In [10]:
data = pd.read_csv(
    'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data',
    sep=r'\s+'
)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [11]:
data['date'] = pd.to_datetime(
    '19' + data['Yr'].astype(str) + '-' +
    data['Mo'].astype(str) + '-' +
    data['Dy'].astype(str)
)

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [12]:
def fix_year(x):
    if x.year > 2000:
        return x.replace(year=x.year - 100)
    return x

data['date'] = data['date'].apply(fix_year)

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [13]:
data = data.set_index('date')
data.index.dtype

dtype('<M8[us]')

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [14]:
data.isna().sum()

Yr     0
Mo     0
Dy     0
RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [15]:
data.notna().sum().sum()

np.int64(98579)

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [16]:
data.mean().mean()

np.float64(14.299199599246569)

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [17]:
loc_stats = data.agg(['min', 'max', 'mean', 'std']).T

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [18]:
day_stats = data.agg(['min', 'max', 'mean', 'std'], axis=1)

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [19]:
data[data.index.month == 1].mean()

Yr     69.500000
Mo      1.000000
Dy     16.000000
RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [20]:
data.resample('YE').mean()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,,,,
1961-12-31,61.0,6.526027,15.720548,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962-12-31,62.0,6.526027,15.720548,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963-12-31,63.0,6.526027,15.720548,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964-12-31,64.0,6.513661,15.756831,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965-12-31,65.0,6.526027,15.720548,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966-12-31,66.0,6.526027,15.720548,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967-12-31,67.0,6.526027,15.720548,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968-12-31,68.0,6.513661,15.756831,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969-12-31,69.0,6.526027,15.720548,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970-12-31,70.0,6.526027,15.720548,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971-12-31,71.0,6.526027,15.720548,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972-12-31,72.0,6.513661,15.756831,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973-12-31,73.0,6.526027,15.720548,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974-12-31,74.0,6.526027,15.720548,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975-12-31,75.0,6.526027,15.720548,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976-12-31,76.0,6.513661,15.756831,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977-12-31,77.0,6.526027,15.720548,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978-12-31,78.0,6.526027,15.720548,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [21]:
data.resample('ME').mean()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,,,,
1961-01-31,61.0,1.0,16.0,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02-28,61.0,2.0,14.5,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03-31,61.0,3.0,16.0,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04-30,61.0,4.0,15.5,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05-31,61.0,5.0,16.0,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08-31,78.0,8.0,16.0,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09-30,78.0,9.0,15.5,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10-31,78.0,10.0,16.0,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11-30,78.0,11.0,15.5,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12-31,78.0,12.0,16.0,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [22]:
data.resample('W').mean()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,,,,
1961-01-01,61.0,1.000000,1.000000,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-08,61.0,1.000000,5.000000,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-15,61.0,1.000000,12.000000,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-22,61.0,1.000000,19.000000,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-29,61.0,1.000000,26.000000,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-03,78.0,11.428571,17.142857,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-10,78.0,12.000000,7.000000,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-17,78.0,12.000000,14.000000,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-24,78.0,12.000000,21.000000,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-31,78.0,12.000000,28.000000,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [23]:
weekly = data.resample('W').agg(['min', 'max', 'mean', 'std'])
weekly.head(52)

            Yr                 Mo                           Dy      ...  \
           min max  mean  std min max       mean       std min max  ...
date                                                                ...
1961-01-01  61  61  61.0  NaN   1   1   1.000000       NaN   1   1  ...
1961-01-08  61  61  61.0  0.0   1   1   1.000000  0.000000   2   8  ...
1961-01-15  61  61  61.0  0.0   1   1   1.000000  0.000000   9  15  ...
1961-01-22  61  61  61.0  0.0   1   1   1.000000  0.000000  16  22  ...
1961-01-29  61  61  61.0  0.0   1   1   1.000000  0.000000  23  29  ...
1961-02-05  61  61  61.0  0.0   1   2   1.714286  0.487950   1  31  ...
1961-02-12  61  61  61.0  0.0   2   2   2.000000  0.000000   6  12  ...
1961-02-19  61  61  61.0  0.0   2   2   2.000000  0.000000  13  19  ...
1961-02-26  61  61  61.0  0.0   2   2   2.000000  0.000000  20  26  ...
1961-03-05  61  61  61.0  0.0   2   3   2.714286  0.487950   1  28  ...
1961-03-12  61  61  61.0  0.0   3   3   3.000000  0.000000   6  12  ...
1961-03-19  61  61  61.0  0.0   3   3   3.000000  0.000000  13  19  ...
1961-03-26  61  61  61.0  0.0   3   3   3.000000  0.000000  20  26  ...
1961-04-02  61  61  61.0  0.0   3   4   3.285714  0.487950   1  31  ...
1961-04-09  61  61  61.0  0.0   4   4   4.000000  0.000000   3   9  ...
1961-04-16  61  61  61.0  0.0   4   4   4.000000  0.000000  10  16  ...
1961-04-23  61  61  61.0  0.0   4   4   4.000000  0.000000  17  23  ...
1961-04-30  61  61  61.0  0.0   4   4   4.000000  0.000000  24  30  ...
1961-05-07  61  61  61.0  0.0   5   5   5.000000  0.000000   1   7  ...
1961-05-14  61  61  61.0  0.0   5   5   5.000000  0.000000   8  14  ...
1961-05-21  61  61  61.0  0.0   5   5   5.000000  0.000000  15  21  ...
1961-05-28  61  61  61.0  0.0   5   5   5.000000  0.000000  22  28  ...
1961-06-04  61  61  61.0  0.0   5   6   5.571429  0.534522   1  31  ...
1961-06-11  61  61  61.0  0.0   6   6   6.000000  0.000000   5  11  ...
1961-06-18  61  61  61.0  0.0   6   6   6.000000  0.000000  12  18  ...
1961-06-25  61  61  61.0  0.0   6   6   6.000000  0.000000  19  25  ...
1961-07-02  61  61  61.0  0.0   6   7   6.285714  0.487950   1  30  ...
1961-07-09  61  61  61.0  0.0   7   7   7.000000  0.000000   3   9  ...
1961-07-16  61  61  61.0  0.0   7   7   7.000000  0.000000  10  16  ...
1961-07-23  61  61  61.0  0.0   7   7   7.000000  0.000000  17  23  ...
1961-07-30  61  61  61.0  0.0   7   7   7.000000  0.000000  24  30  ...
1961-08-06  61  61  61.0  0.0   7   8   7.857143  0.377964   1  31  ...
1961-08-13  61  61  61.0  0.0   8   8   8.000000  0.000000   7  13  ...
1961-08-20  61  61  61.0  0.0   8   8   8.000000  0.000000  14  20  ...
1961-08-27  61  61  61.0  0.0   8   8   8.000000  0.000000  21  27  ...
1961-09-03  61  61  61.0  0.0   8   9   8.428571  0.534522   1  31  ...
1961-09-10  61  61  61.0  0.0   9   9   9.000000  0.000000   4  10  ...
1961-09-17  61  61  61.0  0.0   9   9   9.000000  0.000000  11  17  ...
1961-09-24  61  61  61.0  0.0   9   9   9.000000  0.000000  18  24  ...
1961-10-01  61  61  61.0  0.0   9  10   9.142857  0.377964   1  30  ...
1961-10-08  61  61  61.0  0.0  10  10  10.000000  0.000000   2   8  ...
1961-10-15  61  61  61.0  0.0  10  10  10.000000  0.000000   9  15  ...
1961-10-22  61  61  61.0  0.0  10  10  10.000000  0.000000  16  22  ...
1961-10-29  61  61  61.0  0.0  10  10  10.000000  0.000000  23  29  ...
1961-11-05  61  61  61.0  0.0  10  11  10.714286  0.487950   1  31  ...
1961-11-12  61  61  61.0  0.0  11  11  11.000000  0.000000   6  12  ...
1961-11-19  61  61  61.0  0.0  11  11  11.000000  0.000000  13  19  ...
1961-11-26  61  61  61.0  0.0  11  11  11.000000  0.000000  20  26  ...
1961-12-03  61  61  61.0  0.0  11  12  11.428571  0.534522   1  30  ...
1961-12-10  61  61  61.0  0.0  12  12  12.000000  0.000000   4  10  ...
1961-12-17  61  61  61.0  0.0  12  12  12.000000  0.000000  11  17  ...
1961-12-24  61  61  61.0  0.0  12  12  12.000000  0.000000  18  24  ...

                  CLO              BEL                                MAL  \
                 mean       std    min    max       mean       std    min
date
1961-01-01  12.580000       NaN  18.50  18.50  18.500000       NaN  15.04
1961-01-08   8.497143  1.704941   5.46  17.54  12.481429  4.349139  10.88
1961-01-15   7.571429  4.084293   5.25  20.71  11.125714  5.552215   5.17
1961-01-22   8.124286  4.783952   6.50  15.92   9.821429  3.626584   6.79
1961-01-29  15.640000  3.713368  14.04  27.71  20.930000  5.210726  17.50
1961-02-05   9.460000  2.839501   9.17  19.33  14.012857  4.210858   7.17
1961-02-12  14.440000  1.746749  15.21  26.38  21.832857  4.063753  17.04
1961-02-19  13.542857  2.531361  14.09  29.63  21.167143  5.910938  10.96
1961-02-26  12.730000  4.920064   9.59  23.21  16.304286  5.091162   6.67
1961-03-05  12.370000  1.593685  11.58  23.45  17.842857  4.332331   8.83
1961-03-12  10.458571  3.655113  10.21  22.71  16.701429  4.358759   5.54
1961-03-19  11.627143  3.099472  11.29  22.79  19.350000  3.779727  11.34
1961-03-26  11.481429  2.538224   8.25  21.34  14.037143  4.318069  13.13
1961-04-02   9.631429  3.191115   7.21  18.63  13.471429  4.179854   7.17
1961-04-09   7.238571  2.336182   7.62  17.16  11.712857  3.147781   7.21
1961-04-16   6.178571  2.161137   5.75  16.17   9.482857  3.641464   5.66
1961-04-23   9.551429  3.347972   6.75  19.21  13.620000  4.735096   4.96
1961-04-30   6.124286  2.840568   5.13  13.04   9.720000  2.948237   2.67
1961-05-07  11.585714  3.620819   4.79  28.08  17.548571  8.003490   3.83
1961-05-14   7.822857  5.460237   6.54  18.66  10.421429  3.968272   3.33
1961-05-21   7.114286  2.216889   6.63  12.00   9.624286  1.975853   5.91
1961-05-28   7.535714  2.575661   6.13  14.33  10.518571  3.024524   8.00
1961-06-04   9.035714  2.096989   8.71  17.00  12.298571  2.611139  10.63
1961-06-11   8.397143  2.158323   5.37  16.17  10.148571  3.993062   5.96
1961-06-18   9.594286  3.792400   7.29  25.25  15.351429  6.477887   6.13
1961-06-25  11.257143  2.286218  11.00  19.08  14.370000  2.498386  13.75
1961-07-02  10.268571  1.564144   6.96  21.87  14.535714  6.303747   8.50
1961-07-09  10.547143  3.657179   7.08  20.41  12.220000  4.537988  12.08
1961-07-16  10.157143  3.271899   5.04  20.25  13.520000  4.971060   5.96
1961-07-23   6.041429  1.439785   4.21  10.13   7.524286  2.050218   5.41
1961-07-30   9.470000  4.350268   7.87  22.17  12.841429  5.580903   6.13
1961-08-06   8.951429  2.903018   6.17  18.54  11.595714  4.901377   9.08
1961-08-13   7.235000  2.073777   5.88  14.29  10.934286  2.931302   5.88
1961-08-20  12.244286  2.730237   9.59  21.92  14.922857  4.086725  13.04
1961-08-27  12.507143  3.855302   5.75  23.38  16.251429  6.711322   8.29
1961-09-03   8.924286  3.993736   4.79  24.71  13.664286  7.678051   5.41
1961-09-10   7.565714  3.649278   5.41  15.83  10.700000  4.220584   3.37
1961-09-17  14.268571  5.128338  13.92  23.91  19.878571  4.464252  14.67
1961-09-24   6.798571  2.354092   4.54  20.96  11.018571  5.235868   5.25
1961-10-01  11.840000  3.908397   7.79  21.37  16.208571  5.091268   4.04
1961-10-08   7.662857  4.296870   4.79  17.83   8.810000  4.800403   4.83
1961-10-15   9.494286  3.569308   8.54  20.46  14.451429  4.113200  10.75
1961-10-22  16.461429  5.890511  10.88  24.71  17.477143  5.645871  13.46
1961-10-29  12.952857  6.277629   8.50  27.29  15.592857  7.056150   9.83
1961-11-05  11.864286  2.784450  10.29  20.17  16.322857  4.038493  13.37
1961-11-12   6.415714  2.843518   6.13  12.58   9.208571  2.532196   5.71
1961-11-19   6.031429  4.402588   0.71   9.59   5.875714  3.643285   2.00
1961-11-26   9.582857  2.747452   6.50  20.46  11.772857  5.407223   4.25
1961-12-03   7.911429  3.680477   5.50  19.04  11.464286  5.552648   5.88
1961-12-10  12.022857  4.156207  10.71  21.79  15.975714  4.667933   7.58
1961-12-17  11.058571  4.633398   5.50  22.83  15.112857  6.531043   6.50
1961-12-24   7.697143  4.637096   5.29  17.67   9.958571  5.065308   2.62


              max       mean       std
date
1961-01-01  15.04  15.040000       NaN
1961-01-08  16.46  13.238571  1.773062
1961-01-15  16.92  11.024286  4.692355
1961-01-22  17.96  11.434286  4.237239
1961-01-29  27.63  22.530000  3.874721
1961-02-05  19.25  11.935714  4.336104
1961-02-12  21.84  19.155714  1.828705
1961-02-19  22.58  16.584286  4.685377
1961-02-26  23.87  14.322857  6.182283
1961-03-05  17.54  13.951667  3.021387
1961-03-12  22.54  14.420000  5.769890
1961-03-19  22.95  16.227143  4.331958
1961-03-26  22.50  18.134286  3.701846
1961-04-02  19.58  13.900000  3.924555
1961-04-09  15.34  11.371429  2.598271
1961-04-16  12.87   8.690000  2.747842
1961-04-23  20.46  12.470000  5.908542
1961-04-30  17.50   8.637143  5.108365
1961-05-07  26.58  14.571429  7.728504
1961-05-14  26.30  10.382857  7.858246
1961-05-21  14.96  10.612857  3.310819
1961-05-28  17.04  11.697143  3.811818
1961-06-04  17.96  13.597143  2.593586
1961-06-11  19.83  12.250000  4.925055
1961-06-18  24.71  15.025714  6.242673
1961-06-25  21.50  17.410000  3.063011
1961-07-02  16.79  12.133333  3.652313
1961-07-09  21.29  15.987143  3.665705
1961-07-16  21.96  12.524286  4.974273
1961-07-23  10.92   8.415714  2.133994
1961-07-30  25.37  13.761429  6.664574
1961-08-06  20.25  13.760000  4.448251
1961-08-13  15.16  10.125714  3.356585
1961-08-20  24.30  16.626667  3.934238
1961-08-27  22.29  16.485714  4.947608
1961-09-03  22.54  11.022857  6.308087
1961-09-10  20.25  11.034286  6.049619
1961-09-17  33.09  18.984286  6.332885
1961-09-24  14.62   9.814286  3.113507
1961-10-01  17.16  13.338571  4.696504
1961-10-08  19.62  11.410000  5.462002
1961-10-15  21.04  15.260000  4.098130
1961-10-22  33.45  23.641429  7.468377
1961-10-29  30.88  18.404286  8.340881
1961-11-05  23.58  19.195714  3.870800
1961-11-12  15.54  10.858571  3.690752
1961-11-19  13.25   5.737143  3.787654
1961-11-26  22.58  12.732857  6.475867
1961-12-03  21.29  14.725714  5.233192
1961-12-10  29.33  16.241429  7.345893
1961-12-17  21.12  14.644286  5.665006
1961-12-24  16.62   8.164286  5.048035

[52 rows x 60 columns]